### ISSUE TITLE
Zoom integration

### ISSUE THREAD

**Issue by juanjo-vlc** [manusa/electronim#10]
Hi,

Currently we are using zoom for im, It would be greate having it integrated on electronim.
https://github.com/zoom

**Comment by manusa** [comment]
## Zoom web application has been tested with ElectronIM.

### Start from your  browser

Meetings can be held through "browser" version of the app `start from your browser`:
![Screenshot from 2020-02-01 07-20-25](https://user-images.githubusercontent.com/488391/73587996-5a266a80-44c3-11ea-9d71-6c8488741d51.png)
![image](https://user-images.githubusercontent.com/488391/73588000-71fdee80-44c3-11ea-9615-b3134e0b55f0.png)

Account settings to always enable `start from your browser` link (Profile > Settings):
![Screenshot from 2020-02-01 07-30-45](https://user-images.githubusercontent.com/488391/73588073-c6ee3480-44c4-11ea-9920-b0a2c9787bce.png)
[support.zoom.us > Show a "Join from your browser" Link](https://support.zoom.us/hc/en-us/articles/115005666383-Show-a-Join-from-your-browser-Link)

### Ongoing meeting:
![Screenshot from 2020-02-01 07-26-44](https://user-images.githubusercontent.com/488391/73588054-64953400-44c4-11ea-8e95-e8d894090e0a.png)
![Screenshot from 2020-02-01 07-28-43](https://user-images.githubusercontent.com/488391/73588061-8393c600-44c4-11ea-837e-c70dcd8967cf.png)


### Missing feature > Share Screen

Current missing feature is the option to share screen, but this is common to the rest of the web applications. New issue to be opened to support it.

**Comment by manusa** [comment]
I'm closing this as completed since Zoom should be **fully** functional now on ElectronIM.

Please, feel free to open a new issue in case something is not working for you.
