### ISSUE TITLE
Gmail is missing icons in ElectronIM

### ISSUE THREAD

**Issue by KirilOkun** [manusa/electronim#115]
See attached screenshot.
![Screenshot_20220923_171027](https://user-images.githubusercontent.com/1024870/191939504-eb7512ee-fe97-44e2-88e2-034644de971d.png)

**Comment by KirilOkun** [comment]
This is on Kubuntu,  latest Plasma UI.

**Comment by manusa** [comment]
Duplicate of https://github.com/manusa/electronim/issues/106

Will be fixed in next release
