### ISSUE TITLE
Unable to use GoDaddy email inside ElectronIM

### ISSUE THREAD

**Issue by KirilOkun** [manusa/electronim#119]
I"ve signed up to email service from GoDaddy for some of my domains.   Unfortunately i can't get them to work.   On adding the url and requesting to login it opens a browser page with login but never completes authentication in ElectronIM.  All i see is the activity indicator although it gets authenticated in the browser fine.
Several urls are used with the redirects and i tried them all with the same result:

https://am1.myprofessionalmail.com/appsuite/#!!&app=io.ox/mail&folder=default0/INBOX
https://sso.godaddy.com/?app=email
email.oasistrading.co

**Comment by manusa** [comment]
Hi @KirilOkun 
Could you please confirm that the latest [v0.0.82](https://github.com/manusa/electronim/releases/tag/v0.0.82) release fixes your issue?
