### ISSUE TITLE
Feature request:   Allow to reorder tabs

### ISSUE THREAD

**Issue by KirilOkun** [manusa/electronim#123]
It would be nice if the tabs could be reordered after being added.

**Comment by manusa** [comment]
You can easily reorder tabs by dragging them (just like you would do in any other browser. This is explicitly stated in the application features list.

Are you referring to this?
Is there any way this can be made clearer so that users don't miss this feature?

**Comment by KirilOkun** [comment]
Totally missed that.  My bad.  Was trying to reorder them on the settings page.
