### ISSUE TITLE
Dialog auto-resize should be disabled

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#128]
## Description

The dialog Electorn auto-resize feature should be disabled. Auto-resizing is handled internally by ElectronIM and should not be delegated to Electron's built-in behavior.

The following code:
https://github.com/manusa/electronim/blob/bcb5760d80dd00ec51055e1c404c02ff55eed874/src/browser-window/index.js#L20

Should be replaced by:
```javascript
  browserView.setAutoResize({width: false, horizontal: false, height: false, vertical: false});
```

The test should be updated accordingly too:
https://github.com/manusa/electronim/blob/bcb5760d80dd00ec51055e1c404c02ff55eed874/src/browser-window/__tests/index.test.js#L39-L40

**Comment by Aahil13** [comment]
Good day. I would love to work on this. Please assign it to me

**Comment by Aahil13** [comment]
Good day @manusa. Hope you are doing well today!
I have made the necessary changes to the index.js and index.test.js files.

You can see screenshots below 👇

![index.js](https://user-images.githubusercontent.com/63567230/193732419-0fa4058d-1ae2-4520-8eb7-f19c53c2e4cc.JPG)


![index.test.js](https://user-images.githubusercontent.com/63567230/193732741-ec21b56a-b107-4f22-86a2-feab2db25cd8.JPG)
