### ISSUE TITLE
chrome-tabs auto-resize should be disabled

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#136]
## Description

The chrome-tabs `BrowserView` Electorn auto-resize feature should be disabled. Auto-resizing is handled internally by ElectronIM and should not be delegated to Electron's built-in behavior.

The following code:
https://github.com/manusa/electronim/blob/6b8158e1a6c30acf4e5812c5eefe83b9f83e6d02/src/chrome-tabs/index.js#L49

Should be replaced by:
```javascript
  tabContainer.setAutoResize({width: false, horizontal: false, height: false, vertical: false});
```

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thankyou.
