### ISSUE TITLE
Cannot login to hangouts.google.com

### ISSUE THREAD

**Issue by baldimir** [manusa/electronim#15]
When I try to login to hangouts.google.com, after login I get Google page stating "This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

It might be possible that the user agent should be set to Chrome or similar. [1] 

[1] https://www.omgubuntu.co.uk/2019/12/couldnt-sign-you-in-google-browser-error-linux

**Comment by manusa** [comment]
User agent is already tweaked (but not using Chrome's latest version), will try some alternatives.

**Comment by manusa** [comment]
Login is now possible using standard Google accounts
