### ISSUE TITLE
Remove deprecated nativeWindowOpen option from webPreferences in help module

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#152]
## Description

The help `BrowserView` Electron `webPreferences.nativeWindowOpen` option should be removed since it has been [deprecated](https://www.electronjs.org/blog/electron-18-0#removed-nativewindowopen) and [removed from the API](https://github.com/electron/electron/pull/29405).

The following code:
https://github.com/manusa/electronim/blob/78f1a60e92914d4804bcb7ad609ee46ce32fcac8/src/help/index.js#L21-L27

Should be replaced by:
```javascript
const webPreferences = {
  contextIsolation: false,
  nodeIntegration: false,
  sandbox: true,
  preload: path.resolve(__dirname, '..', '..', 'bundles', 'help.preload.js')
};
```

**Comment by chinmaym07** [comment]
Hey @manusa Can I do this ?
