### ISSUE TITLE
Remove deprecated nativeWindowOpen option from webPreferences in chrome-tabs module

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#155]
## Description

The help `BrowserView` Electron `webPreferences.nativeWindowOpen` option should be removed since it has been [deprecated](https://www.electronjs.org/blog/electron-18-0#removed-nativewindowopen) and [removed from the API](https://github.com/electron/electron/pull/29405).

The following code:
https://github.com/manusa/electronim/blob/52c0cd63205bcae4cabfb3aa4d98712e337300c0/src/chrome-tabs/index.js#L23-L30

Should be replaced by:
```javascript
const webPreferences = {
  contextIsolation: false,
  nodeIntegration: false,
  sandbox: true,
  preload: path.resolve(__dirname, '..', '..', 'bundles', 'chrome-tabs.preload.js'),
  partition: 'persist:electronim'
};
```

**Comment by buneeIsSlo** [comment]
@manusa Hi, I can work on this.
