### ISSUE TITLE
Tabs share the same context

### ISSUE THREAD

**Issue by baldimir** [manusa/electronim#16]
Currently the application behaves as a single browser, sharing data across tabs. Would it be possible to allow each tab to have its own data context? I mean if I log in to some Google service in one tab, and want to log in to some other Google service in a second tab, I am already logged in with the account from the first tab.

**Comment by manusa** [comment]
That's a perfectly valid use case.
It also interferes with the opposite behavior, "I logged in to one service in a tab and want to reuse this session", which is also valid.
Maybe adding a checkbox in the settings panel to indicate that the tab should be "sandboxed"/isolated could be a win-win.

**Comment by baldimir** [comment]
Agree both use cases are valid. The checkbox sounds good.

**Comment by manusa** [comment]
Feature is ready

You can enable an isolated context/session by closing the lock (click to toggle) on the settings page for your tab:
![image](https://user-images.githubusercontent.com/488391/86558787-9bcbad80-bf5a-11ea-823c-cd278b53d066.png)
![image](https://user-images.githubusercontent.com/488391/86558772-91a9af00-bf5a-11ea-8ba6-bc86bd3f83ba.png)

When the lock is closed (sandboxed tab), a specific session for that tab will be created.

All tabs with an open lock (unsandboxed tabs) share the same session.

**Comment by baldimir** [comment]
Perfect. Thank you very much!
