### ISSUE TITLE
add shortcut Ctrl+Tab and Ctrl+Shift+Tab

### ISSUE THREAD

**Issue by pedro-nonfree** [manusa/electronim#161]
Tabs traversing with the keyboard are pretty generic on firefox, chrome, etc. and I was expecting to work in this (nice!) application. They are very useful to avoid using the mouse to click and traverse through different messages on different platforms

**Comment by manusa** [comment]
Yep, this one should be easy to implement. I'll try to add it to the upcoming release.

Thx for your feedback.

**Comment by manusa** [comment]
I'm implementing this as `ctrl+tab` and `shift+ctrl+tab` for every platform, including macOS (maybe this convention assumption is wrong).

**Comment by pedro-nonfree** [comment]
thank you @manusa tried it on v0.0.83 and it works great :heart:
