### ISSUE TITLE
Standalone version of ElectronIM for macOS not working

### ISSUE THREAD

**Issue by visomar** [manusa/electronim#17]
When downloading the macos version of the current release (0.0.54) and trying to execute it, two issues arise:

1. Security and Privacy:
 when launching the application for the first time, the usual warning of unknown origin or developer appears: 
 > "ElectronIM" cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.
 
<img width="658" alt="standalone 2020-02-26 10-20-49" src="https://user-images.githubusercontent.com/7437402/75331513-24d32980-5883-11ea-8fc2-30963ee75998.png">
 To solve this issue, go to Apple menu  > System Preferences, click Security & Privacy, then click General. In the window that appears it should appear a message stating that the application has been blocked, and a button to let the [admin] user open it.

 ![Apple 2020-02-26 10-18-47](https://user-images.githubusercontent.com/7437402/75331859-b6429b80-5883-11ea-9f39-5b9a5c8f8214.png)
 ![Security   Privacy 2020-02-26 10-21-20](https://user-images.githubusercontent.com/7437402/75331866-b93d8c00-5883-11ea-9d71-3dfc21212a06.png)

 @manusa feel free to include the description as well as my screenshots in the troubleshooting section of your application if you wish to

2. When the user is finally able to launch the application, an error message appears:

> ElectronIM cannot be opened because of a problem.
Check with the developer to make sure ElectronIM works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.
[...]

 ![Monosnap 2020-02-26 10-40-46](https://user-images.githubusercontent.com/7437402/75332350-86e05e80-5884-11ea-8198-e3bebcee4081.png) 

Best regards

**Comment by manusa** [comment]
Ho @visomar,

Thanks a lot for your input and thorough description :heart:.

We can add this to the documentation.

However, I'll try to make myself a trusted developer (at least in the eyes of Apple) :stuck_out_tongue:. I'll probably include a valid and trustable dmg package.

**Comment by manusa** [comment]
DMG archives are now created upon release.

I borrowed a macOS laptop and managed to test the application (bypassing security) but BrowserViews are not working as expected (some issues when resizing).

If I can get hold of a macOS system for a couple of days I'll try to fix it, else PRs are welcome ;).

> ...However, I'll try to make myself a trusted developer (at least in the eyes of Apple)...

Being a trusted Apple developer takes at least [99 USD/year](https://developer.apple.com/support/purchase-activation/), which I'm not willing to spend right now. So this action point will have to wait.

**Comment by visomar** [comment]
I did notice the BrowserViews not working (it also gets blank when coming back from the setting, if I remember correctly), but I guess that's for another issue...
I'll test the DMG file created in the latest release, and let you know if it works.

P.S.: I need to get a little bit more in touch with electron, but if I do, I'll try and test what is happening with the view in macOS. In the meantime, if you need me to test anything in it, just let me know.

**Comment by visomar** [comment]
Checked, and DMG version for macOS now runs the program properly.
