### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#176]

**Comment by manusa** [comment]
Ideas:
![image](https://user-images.githubusercontent.com/488391/199654759-ad805d32-3507-4988-aef1-8513c21af657.png)
![image](https://user-images.githubusercontent.com/488391/199654862-0b6d0700-e5cb-42f6-b736-7c22030cb78e.png)
![image](https://user-images.githubusercontent.com/488391/199654901-a5821e2f-9d59-4486-bd53-a5bf8c0f308b.png)
![image](https://user-images.githubusercontent.com/488391/199654937-b2a1f853-7ee4-420b-a20d-6b1396758063.png)
![image](https://user-images.githubusercontent.com/488391/199654992-239b067d-aa27-4764-82e3-22f3b84eabeb.png)
![image](https://user-images.githubusercontent.com/488391/199655214-9409bb3b-d4f3-4b6c-938a-b7766c297961.png)
![image](https://user-images.githubusercontent.com/488391/199655235-1ea5187d-34c7-4dec-9aa9-eaf6b0b472d9.png)
![image](https://user-images.githubusercontent.com/488391/199655390-b66db2ef-d568-4698-bb68-683eaebdbb01.png)
![image](https://user-images.githubusercontent.com/488391/199655459-cfcae07a-bb82-4ad0-95fb-e88c121e2290.png)
![image](https://user-images.githubusercontent.com/488391/199655517-e46f7fa6-a221-490d-ba3f-dac15d641f61.png)




Bubble with an electron (-) sign orbiting.

**Comment by pedro-nonfree** [comment]
The most I like is

![image](https://user-images.githubusercontent.com/39959198/199702180-ac297bdd-4597-4aa6-9108-5396ea092307.png)

because it looks simple (white background, soft coloring), and that matches with the philosophy of this project, providing a grid of IM in an easy manner. Also, I like the logo, it is electron, but its projection is an squared grid. A square give sense of order, that you put order on your communications (IM) - and that matches the most how I feel after using your app :)

**Comment by 8227846265** [comment]
Voting for this one as well.
![image](https://user-images.githubusercontent.com/66582769/202891880-c368d5f4-80ff-49a5-a5c9-bb0ce658c98a.png)

**Comment by manusa** [comment]
> Voting for this one as well. ![image](https://user-images.githubusercontent.com/66582769/202891880-c368d5f4-80ff-49a5-a5c9-bb0ce658c98a.png)

Initial draft of the icon was already implemented and is based on this option.

![image](https://raw.githubusercontent.com/manusa/electronim/c286fa8fb3e39a4b4d2ed975feaa013686c50c2f/assets/logo.svg)

You can check the resulting image in the latest release on the about dialog too.



For the tray and window icon a different had to be implemented to make it visible as 16x16 pixel image.


![image](https://raw.githubusercontent.com/manusa/electronim/c286fa8fb3e39a4b4d2ed975feaa013686c50c2f/assets/icon.svg)
