### ISSUE TITLE
Escape don't working in any tabs & Login problems

### ISSUE THREAD

**Issue by ZeX1SSX** [manusa/electronim#263]
**Hi, from time in use, I find 2 problems**

### 1.  Escape don't working in tabs
**Escape do close chat in tab, on this app this shortcut don't working**

### 2. Login problem
**I have problem with login to sites who open new tab for complete authficitaion.
For solve i copy auth link (opened in browser), and paste it to tab throught edit link menu.**

> Tested on 2 PC's - Windows 10 x64 - Intel & AMD

**Comment by manusa** [comment]
1. should be taken care of
2. I'm still working on/thinking of a generic, easy to use, and intuitive solution, can be tracked on #42 (curious number BTW)
