### ISSUE TITLE
.config/electronim/CodeCache/js growing ...

### ISSUE THREAD

**Issue by se7en-x230** [manusa/electronim#266]
Cache and Code Cache is almost 700MB !!!!

![shop-2023-01-16-18-50](https://user-images.githubusercontent.com/69777713/212671788-edd79dde-8991-4619-a94b-41155297a165.png)

**Comment by manusa** [comment]
These are Electron internal directories. I'm not 100% sure about this, but they can be safely removed without further consequences.

As an improvement, we can consider adding an advanced option to delete these directories, or the data in these directories (however, this would clutter the UI). Another option can be to remove these directories or their data each time the application is started or closed.

**Comment by se7en-x230** [comment]
The start/close clean option sounds sane.

**Comment by manusa** [comment]
The new [v0.0.89](https://github.com/manusa/electronim/releases/tag/v0.0.89) release includes a fix that will clear the cache every time you exit the app.

@se7en-x230, can you please confirm this feature is aligned with your expectations and that the app directory has stopped growing (and probably shrinked too)?
