### ISSUE TITLE
Each tab should land to own sandbox to allow run multiple instances of the same IM.

### ISSUE THREAD

**Issue by hetii** [manusa/electronim#268]
Hello.

In my case I need to run multiple teams instances where each of handle another clients.

It seams that each teams instance is aware about another one and not allow to handle multiple subscription.
So at the end each tab/service should be isolated into own sandbox and not affect another one.

**Comment by manusa** [comment]
This is exactly what the [sandboxing](https://github.com/manusa/electronim/blob/main/docs/Setup.md#sandboxing) option is used for.

Have you tried it? does it work for you?

**Comment by hetii** [comment]
@manusa Yea, somehow I missed this ;)
After enabled it my teams works as expected.
