### ISSUE TITLE
Telegram unable to scroll chat

### ISSUE THREAD

**Issue by se7en-x230** [manusa/electronim#285]
Telegram unable to scroll chat
Also the scrollbar is missing 

looks like deleting the tab and saving it fixed the problem

**Comment by manusa** [comment]
I had this issue with version Z of Telegram web. Switching to K fixed the issue.

It appears that version Z might have had some bugs. It seems to be fixed now though.

**Comment by se7en-x230** [comment]
Thanks didn't think about trying that.

Switched over and suddenly the UI is responsive again.
I will test it and report.
