### ISSUE TITLE
Two WhatsApp accounts 

### ISSUE THREAD

**Issue by DMahmoodi** [manusa/electronim#326]
I have two WahtsApp acounts. Unlike Ferdi, I cannot open both of them in Electronim at the same time! I could not check other services like Yahoo that I have two of.  I also have to say this app is a  Fantastic job

**Comment by manusa** [comment]
Hi @DMahmoodi,

This is exactly what the [sandboxing](https://github.com/manusa/electronim/blob/main/docs/Setup.md#sandboxing) option is used for.

Have you tried it? does it work for you?


There are many users who keep running into this issue. I'm out of ideas on how to make this clearer. 
Any suggestion to make this clearer from the user's perspective is welcome :wink:

_Same as_
- #268 
- #48

**Comment by manusa** [comment]
I assume that the sandbox option did make the job. If you have further suggestions on how to improve the user experience so that others don't face this issue, please feel free to add a comment or create a new issue.
