### ISSUE TITLE
Whatsapp works with Chrome 60+

### ISSUE THREAD

**Issue by RDKclick** [manusa/electronim#327]
I am a developer using electron and came across Whatsapp works with Chrome 60+. How to solve it?

**Comment by RDKclick** [comment]
![image](https://github.com/manusa/electronim/assets/43614679/c0ba4029-cc6a-49d5-955c-b818e406c6da)

**Comment by manusa** [comment]
Do you mean that you're getting this issue in ElectronIM, or that you want to understand how this is solved here?

**Comment by manusa** [comment]
It's been several months since you asked this but you didn't follow up on my request for elaboration and clarification.
Closing the issue now, feel free to open a new one in case you still think that your request is applicable.
