### ISSUE TITLE
spell-check: Promise returned in function argument where a void return was expected.

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#352]
## Description

The following code has been marked as a [bug](https://sonarcloud.io/project/issues?open=AYh_YKsxW2wJeQETzpxV&id=manusa_electronim):

https://github.com/manusa/electronim/blob/9794439336e2b9130a5dc6cfd8f26c66405ac8ea/src/tab-manager/preload.spell-check.js#L19-L23

It should be changed to:

```javascript
const spellCheckFunction = (words, callback) => {
  // eslint-disable-next-line no-undef
  ipcRenderer.invoke(APP_EVENTS.dictionaryGetMisspelled, words)
    .then(misspelled => callback(misspelled));
};
```

**Comment by maazshakeel** [comment]
@manusa  Hey, I'd love to work on this issue, can you assign it to me?

**Comment by maazshakeel** [comment]
Made a pull request:
https://github.com/manusa/electronim/pull/355#issue-1939362698

Would appreciate the feedback! 🙌
