### ISSUE TITLE
preload.mediadevices-shim: Promise returned in function argument where a void return was expected.

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#360]
## Description

The following code has been marked as a [bug](https://sonarcloud.io/project/issues?open=AYh_YKsnW2wJeQETzpxS&id=manusa_electronim):

https://github.com/manusa/electronim/blob/0ad1c686c3461dbec38bd6aa1bb2feae3c86857a/src/tab-manager/preload.mediadevices-shim.js#L148-L151

It should be changed to:

```javascript
  const updateSourcesFunction = () => {
    desktopCapturer.getSources(DEFAULT_SOURCES_OPTIONS).then(setSources);
  };
  useEffect(() => {
    setTimeout(updateSourcesFunction, sources ? 300 : 0);
  }, [sources]);
```

Please **note** that for the tests to pass correctly, the following lines:

https://github.com/manusa/electronim/blob/0ad1c686c3461dbec38bd6aa1bb2feae3c86857a/src/tab-manager/preload.mediadevices-shim.js#L27-L30

need to be changed to:

```javascript
const desktopCapturer = {
  // eslint-disable-next-line no-undef
  getSources: async opts => ipcRenderer.invoke(APP_EVENTS.desktopCapturerGetSources, opts)
};
```

**Comment by vishnukaushik** [comment]
@manusa Could you please assign this task to me? I can work on it
Thanks!

**Comment by manusa** [comment]
sure, thx!

**Comment by vishnukaushik** [comment]
@manusa, I've raised a PR to solve this issue. Could you please take a look when you get a chance?
Thank you!

**Comment by vishnukaushik** [comment]
I need maintainers' approval for the PR workflow to kick off
