### ISSUE TITLE
How to start the project?

### ISSUE THREAD

**Issue by Flyooofly** [manusa/electronim#37]
Hello,I'm a learner of electron,and I want to know why I cd the project and then use "npm start", but get a blank page?
![image](https://user-images.githubusercontent.com/31236750/100405610-e6cb9600-309e-11eb-95c3-1a4f3360b84c.png)

**Comment by manusa** [comment]
Probably you're forgetting the `npm install` part.

The following sequence should work to get started:
```shell script
$ git clone git@github.com:manusa/electronim.git
$ cd electronim
$ npm install
$ npm start
```

Debugging and other dev tasks are harder since electron uses different threads>processes.

**Comment by Flyooofly** [comment]
> Probably you're forgetting the `npm install` part.
> 
> The following sequence should work to get started:
> 
> ```shell
> $ git clone git@github.com:manusa/electronim.git
> $ cd electronim
> $ npm install
> $ npm start
> ```
> 
> Debugging and other dev tasks are harder since electron uses different threads>processes.

Thanks，it works。
