### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by dionorgua** [manusa/electronim#45]
As far as I see currently app uses hardcoded stylesheet. I mostly don't care about settings stuff, but it should be possible to use dark theme for tab bar.

**Comment by manusa** [comment]
Fixed in:
- #124
- #126
- #127 
- #131

**Comment by manusa** [comment]
Hi @dionorgua  
Could you please confirm that the latest [v0.0.82](https://github.com/manusa/electronim/releases/tag/v0.0.82) release fixes your issue?
