### ISSUE TITLE
support multi account

### ISSUE THREAD

**Issue by dennyhalim** [manusa/electronim#48]
i'll be greater than great to support multiple account
so we can log into multiple facebook / telegram / whatever account

anyway, thanks for the great app!

**Comment by manusa** [comment]
Hi @dennyhalim 
Multiple accounts for any service are already available.
You can achieve this by using the `Sandbox` checkbox in the settings for your application:
![image](https://user-images.githubusercontent.com/488391/113500658-09276180-9520-11eb-8e70-ebd054ec5f50.png)
![image](https://user-images.githubusercontent.com/488391/113500663-117f9c80-9520-11eb-849c-79a06f3f2637.png)

When the checkbox is unchecked, the same context will be shared across all of the tabs (i.e. you only need to log in once for any providers which provide multiple services: GMail, Google Chat, etc.)

When the checkbox is checked, a separate isolated context will be created for that specific tab, so you can open one **or more** tabs for the same application with different accounts.

Maybe this point is unclear in the documentation. Would you like to contribute a section in the [Setup guide - Settings section](https://github.com/manusa/electronim/blob/master/docs/Setup.md#settings)?

(same as #16)

**Comment by leogallego** [comment]
Hi @manusa , I just added the suggested changes to the docs in pull 57 and also included a section for the AppImage package.
