### ISSUE TITLE
Snap doesn't work on Wayland

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [manusa/electronim#65]
```
 ~/Downloads  snap run electronim --enable-features=UseOzonePlatform --ozone-platform=wayland 1898ms  ma 11 okt 2021 14:50:51 CEST
[77899:1011/145056.530966:ERROR:wayland_connection.cc(180)] Failed to connect to Wayland display
[77899:1011/145056.530996:FATAL:ozone_platform_wayland.cc(211)] Failed to initialize Wayland platform
fish: Job 1, 'snap run electronim --enable-fe…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

Tested on ArchLinux (with the latest updates available available as of november 11th 2021), Snap 2.53 and Sway. `WAYLAND_DISPLAY` env var is correctly set.

**Comment by manusa** [comment]
Hi @h3x4d3c1m4l,
Did this happen after the latest release ([0.0.74](https://github.com/manusa/electronim/releases/tag/v0.0.74)), or was this an issue on previous versions too?

**Comment by manusa** [comment]
OK, I thought you were an old-time user.

Snap sandbox is quite restrictive, so I'm not sure it plays nicely with Wayland.

I would recommend to go for the [Appimage distribution](https://github.com/manusa/electronim/releases/download/v0.0.74/electronim-linux-x86_64.AppImage) instead?
