### ISSUE TITLE
New version available notification (check for updates)

### ISSUE THREAD

**Issue by manusa** [manusa/electronim#97]
## Description

Users of the application should be notified whenever a new version is available to download. This is especially useful for those who run a standalone version of the application that is not managed by a package manager.

**Comment by KirilOkun** [comment]
I've installed electronim with Snap.   "snap refresh electronim" comes back with "no updates available".     When will the snap package be available with the latest changes?   
Thanks.

**Comment by manusa** [comment]
> I've installed electronim with Snap. "snap refresh electronim" comes back with "no updates available". When will the snap package be available with the latest changes? Thanks.

The version is usually available minutes after the release is complete. The latest version (0.0.81) is already available from Snapcraft (https://snapcraft.io/electronim). Are you sure your version is not updated? (you can check the actual version in the Help dialog or the Settings dialog - end of the page)

**Comment by KirilOkun** [comment]
Got 0.0.81.  So all good.  Somehow i missed the update.
